/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as oracleInterfaceSol from "./OracleInterface.sol";
export { AggregatorV2V3Interface__factory } from "./AggregatorV2V3Interface__factory";
export { BEP20Interface__factory } from "./BEP20Interface__factory";
export { VBep20Interface__factory } from "./VBep20Interface__factory";
