/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockPivotOracle } from "./MockPivotOracle";
export type { MockSimpleOracle } from "./MockSimpleOracle";
