/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { VenusChainlinkOracle } from "./VenusChainlinkOracle";
export type { VenusOracle } from "./VenusOracle";
