/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockSimpleOracleSol from "./MockSimpleOracle.sol";
export type { mockSimpleOracleSol };
export type { BEP20Harness } from "./BEP20Harness";
export type { MockV3Aggregator } from "./MockV3Aggregator";
export type { VBEP20Harness } from "./VBEP20Harness";
