/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPancakeV2Callee,
  IPancakeV2CalleeInterface,
} from "../../../../contracts/test/PancakePair.sol/IPancakeV2Callee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "pancakeV2Call",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPancakeV2Callee__factory {
  static readonly abi = _abi;
  static createInterface(): IPancakeV2CalleeInterface {
    return new utils.Interface(_abi) as IPancakeV2CalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPancakeV2Callee {
    return new Contract(address, _abi, signerOrProvider) as IPancakeV2Callee;
  }
}
