/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bep20HarnessSol from "./BEP20Harness.sol";
export * as mockAggregatorOracleSol from "./MockAggregatorOracle.sol";
export { VBEP20Harness__factory } from "./VBEP20Harness__factory";
