/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bep20HarnessSol from "./BEP20Harness.sol";
export type { bep20HarnessSol };
import type * as mockAggregatorOracleSol from "./MockAggregatorOracle.sol";
export type { mockAggregatorOracleSol };
export type { VBEP20Harness } from "./VBEP20Harness";
