/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { OracleInterface__factory } from "./OracleInterface__factory";
export { PivotOracleInterface__factory } from "./PivotOracleInterface__factory";
