/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OracleInterface,
  OracleInterfaceInterface,
} from "../../../../contracts/interfaces/OracleInterface.sol/OracleInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "vToken",
        type: "address",
      },
    ],
    name: "getUnderlyingPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class OracleInterface__factory {
  static readonly abi = _abi;
  static createInterface(): OracleInterfaceInterface {
    return new utils.Interface(_abi) as OracleInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OracleInterface {
    return new Contract(address, _abi, signerOrProvider) as OracleInterface;
  }
}
