/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PivotValidator,
  PivotValidatorInterface,
} from "../../../../contracts/interfaces/OracleInterface.sol/PivotValidator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "vToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "validatePrice",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PivotValidator__factory {
  static readonly abi = _abi;
  static createInterface(): PivotValidatorInterface {
    return new utils.Interface(_abi) as PivotValidatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PivotValidator {
    return new Contract(address, _abi, signerOrProvider) as PivotValidator;
  }
}
