/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  PivotOracleInterface,
  PivotOracleInterfaceInterface,
} from "../../../../contracts/interfaces/OracleInterface.sol/PivotOracleInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "vToken",
        type: "address",
      },
    ],
    name: "getUnderlyingPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "vToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
    ],
    name: "validatePrice",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PivotOracleInterface__factory {
  static readonly abi = _abi;
  static createInterface(): PivotOracleInterfaceInterface {
    return new utils.Interface(_abi) as PivotOracleInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PivotOracleInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PivotOracleInterface;
  }
}
